# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sigC3 <- function(dLtil, K, T, N, id, H) {
    .Call(`_pEPA_sigC3`, dLtil, K, T, N, id, H)
}

